/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find total customers by country
SELECT country, COUNT(customer_id) total_customers
FROM gold.dim_customers
GROUP BY 1
ORDER BY 2 DESC

-- Find total customers by gender
SELECT gender, COUNT(customer_id) total_customers
FROM gold.dim_customers
GROUP BY 1
ORDER BY 2 DESC

-- Find total products by category
SELECT category, COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY 1
ORDER BY 2 DESC

-- What is the average cost in each category?
SELECT category, AVG(cost) avg_costs
FROM gold.dim_products
GROUP BY 1
ORDER BY 2

-- What is the total revenue generated for each category?
SELECT b.category, SUM(sales_amount) total_revenue
FROM gold.fact_sales
LEFT JOIN gold.dim_products b
USING(product_key)
GROUP BY 1
ORDER BY 2 DESC

-- Find total revenue generated by each customer
SELECT b.customer_number, b.first_name, b.last_name, SUM(sales_amount) total_revenue
FROM gold.fact_sales
LEFT JOIN gold.dim_customers b
USING(customer_key)
GROUP BY 1, 2, 3
ORDER BY 4 DESC
LIMIT 10

-- What is the distribution of sold items accross countries?
SELECT b.country, SUM(quantity) sold_items
FROM gold.fact_sales
LEFT JOIN gold.dim_customers b
USING(customer_key)
GROUP BY 1
ORDER BY 2 DESC
